FROM python:3.13-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc \
    libpq-dev \
    && rm -rf /var/lib/apt/list/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

RUN python -m nltk.downloader punkt_tab

COPY migrations.sh .
RUN chmod +x migrations.sh
RUN ./migrations.sh

COPY . .
EXPOSE 8000

CMD ["gunicorn", "instrumate.asgi:application", "-k", "uvicorn_worker.UvicornWorker"]
